on:
  pull_request:
    branches: main
  schedule:
    - cron: "0 4 * * *"

name: Check/Codecov/Update Table

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: R CMD Check (${{ matrix.config.os }} (${{ matrix.config.r }}))

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release" }
          - { os: windows-latest, r: "3.6" }
          - { os: windows-latest, r: "devel" }
          - { os: macOS-latest, r: "release" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          set -x
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Install Python
        run: |
          remotes::install_github('rstudio/reticulate')
          reticulate::install_miniconda()
          remotes::install_local()
          install.packages('keras')
          keras::install_keras(tensorflow = '2.0.1', extra_packages = c('IPython', 'requests', 'certifi', 'urllib3', 'tensorflow-hub', 'tabnet==0.1.4.1'))
          reticulate::py_install(c('torch', 'pycox'), pip = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Install covr
        if: ${{ github.event_name == 'pull_request' }}
        run: install.packages('covr')
        shell: Rscript {0}

      - name: Test coverage
        if: ${{ github.event_name == 'pull_request' }}
        run: covr::codecov()
        shell: Rscript {0}

      - name: Render rmd
        if: ${{ github.event_name == 'pull_request' && success() }}
        run: rmarkdown::render('README.Rmd')
        shell: Rscript {0}
        
      - name: Commit changes
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update README.md'
          add: 'README.md'
          
